cookie_secret: hellogithub

development: true

database: db/pomospace.db

admin_username: 'elonmusk'
admin_password: 'spacexrocks'

# Will use this if development: false
confirm_mail_from: ''
confirm_mail_to: ''
